name: AUTO

on:
  push:
    branches: 
      - test.md
      #'*.md'
jobs:
    createPullRequest:
      runs-on: ubuntu-latest
      # if: contains(github.event.head_commit.message, 'Done')
      steps:
        - uses: actions/checkout@v2
          
        - name: Create Pull Request
          id: cpr
          uses: peter-evans/create-pull-request@v2.8.0
          with: 
            commit-message: Add report file
            committer: GitHub <noreply@github.com>
            author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
            title: '[Example] Add report file'
            body: |
              New report
            draft: true
            branch: auto
            request-to-parent: false
        - name: Check outputs
          run: |
            echo "Pull Request Number"
